### ISSUE TITLE
MU_ENUM_TO_STRING should return NULL (%d) when the enum identifier cannot be matched

### ISSUE THREAD

**Issue by mattdurak** [Azure/azure-macro-utils-c#32]
Currently it always returns the string "NULL" as the default case, but then the information about the invalid enum value is not reported.

**Comment by anporumb** [comment]
Well - it returns `UNKNOWN` and prints the decimal value of the enum.
Like this
```code
Line:147 unexpected result=UNKNOWN (4)
```
